version: "2"
services:
  app:
    container_name: "app"
    restart: always
    build: .
    environment:
      - MONGO_URI=mongodb://mongo/condor-psl
      - PORT=3000
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    command: npm start

  mongo:
    container_name: "mongo"
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null